set :domain, 'alpha.jumpstart.ge'
set :user, 'prisoners-staging'
set :application, 'Starter-Template-Production'
set :repository, 'git@github.com:nwshane/starter-template-test.git'
set :web_url, 'rails4-deploy.jumpstart.ge'
